[tool.poetry]
name = "smah"
version = "0.1.0"
description = ""
authors = ["Keith Brings <keith.brings@noizu.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
